project_id = "pooeaxqkysmngpnpnswn"

[functions.market-research]
verify_jwt = true

[functions.search-business]
verify_jwt = true

[functions.scrape-website-details]
verify_jwt = true

[functions.scrape-competitor-avatar]
verify_jwt = true

[functions.sentiment-analysis-run]
verify_jwt = true

[functions.facebook-connect]
verify_jwt = true

[functions.google-sheets-connect]
verify_jwt = true

[functions.ad-spy-scrape]
verify_jwt = true

[functions.ad-spy-recreate]
verify_jwt = true
