project_id = "pooeaxqkysmngpnpnswn"

[functions.market-research]
verify_jwt = true

[functions.sentiment-analysis-run]
verify_jwt = true

[functions.facebook-connect]
verify_jwt = true

[functions.google-sheets-connect]
verify_jwt = true
